name: Integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -DDEBUG=1 .

    - name: Build
      run: make test

    - name: Run integration tests
      working-directory: ${{github.workspace}}
      run: ./test -i